/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SyronFS;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        SyronFS fileSystem = new SyronFS();
        fileSystem.handleQueries();
    }
}
